---
on: push

jobs:
  build:
    name: Build Python bindings for libguestfs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout libguestfs sources
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          ref: stable-1.56
          repository: libguestfs/libguestfs
          submodules: true

      - name: Update package name for uploading to PyPI
        run: sed -i '/^setup/s/\bguestfs\b/pyguestfs/' python/setup.py.in

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install Python packaging dependencies
        run: pip3 install --user setuptools

      - name: Enable deb-src repositories
        run: 'sudo sed -i "s/^Types: deb$/Types: deb deb-src/" /etc/apt/sources.list.d/ubuntu.sources'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y build-dep libguestfs && sudo apt-get -y install libjson-c-dev

      - name: Update kernel permissions to allow reading
        run: sudo chmod 0644 /boot/vmlinuz*

      - name: Enable access to the KVM device
        run: sudo chmod 0666 /dev/kvm

      - name: Autoreconf
        run: autoreconf -fiv

      - name: Configure build
        run: ./configure --disable-gobject

      - name: Build libguestfs
        run: make V=1 REALLY_INSTALL=yes -j install

      - name: Build bindings sdist
        run: make V=1 INSTALLDIRS=vendor -C python sdist

      - name: Test installation of bindings
        run: pip3 install --user python/dist/guestfs-*.tar.gz

      - name: Store built Python bindings
        uses: actions/upload-artifact@v4
        with:
          name: pyguestfs-package-distributions
          path: python/dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pyguestfs
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: pyguestfs-package-distributions
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyguestfs
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: pyguestfs-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
